### ISSUE TITLE
Allow pickup deliveries

### ISSUE THREAD

**Issue by daniquilez** [coopdevs/lazona_connector#127]
The idea is to find out the way trough the order webhook if a product delivery doesn't need to go to Koiki and if it can be just be picked up locally at the store.

**Comment by numeropi** [comment]
After researching, I found https://docs.woocommerce.com/document/local-pickup/

where allows to configure the local pickup BUT for any purchase of any vendor Woocomerce vendors(since the multivendor is a 3rd party plugin.)

![image](https://user-images.githubusercontent.com/56868560/131870118-c677a607-0ca6-40ce-be52-f97f1dcbf62e.png)

Then i researched about the capabilities of the installed WCFM plugin https://docs.wclovers.com/store-shipping/
and after a bit of help in:

https://wclovers.com/forums/topic/no-shipping-zone-found-for-configuration-please-contact-with-admin-for-manage-y/

![image](https://user-images.githubusercontent.com/56868560/131878382-45c1475a-a006-431c-9435-50b2b14d56d6.png)

i was able to setup the a local pickup shipment and "flat fee" shipping, for a specific vendor.
![image](https://user-images.githubusercontent.com/56868560/131878436-398d20fe-2da4-49d8-b805-65846125cfde.png)

which allows to select during the checkout moment.
![image](https://user-images.githubusercontent.com/56868560/131880173-ec4feb08-7230-41b2-91e2-cf43e65f2bea.png)


I still need to find out how I can make the Koiki shipment appear for a vendor to choose too.

**Comment by numeropi** [comment]
After researching a bit further we found out that we can edit the name of this "Flat rate shipping" methods through the vendor's shipping panel.

![image](https://user-images.githubusercontent.com/56868560/132028063-9ae79e70-0ac6-46e8-a02b-5a89020e95bd.png)

After checking out the order, we could differentiate the shipping methods from the new order webhook like this:

Same product but order being shipped trough Koiki's:
![image](https://user-images.githubusercontent.com/56868560/132029723-be0eb309-cb91-463b-aba6-48f92daa85d1.png)

and the one to be picked up locally (no shipped with Koiki)
![image](https://user-images.githubusercontent.com/56868560/132029904-b6755f4f-9cf4-471e-8dc5-042afc57b109.png)
![image](https://user-images.githubusercontent.com/56868560/132029931-628a7bf3-358d-4370-8d43-28b6291b3bf0.png)
